# .github/workflows/release-please.yml
name: Release Please

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  check-workflow:
    runs-on: ubuntu-latest
    # Add this step to debug workflow_run event
    steps:
      - name: Debug workflow_run event
        env:
          EVENT_JSON: ${{ toJSON(github.event) }}
        run: |
          echo "Workflow run event details:"
          echo "$EVENT_JSON"
          echo "Source branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"

  release-please:
    needs: check-workflow
    # Modify condition to check head_branch
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'test-release')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          default-branch: ${{ github.event.workflow_run.head_branch }}
          release-type: node
          package-name: surfgrad
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Refactor","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"test","section":"Tests","hidden":true}
            ]

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      # Add dry run step before actual publish
      - name: NPM Publish
        run: npm publish --dry-run
        if: ${{ steps.release.outputs.release_created }}