# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - main
      - test-release
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  release-please:
    # Run on direct pushes OR successful test workflow completions
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          default-branch: ${{ github.event_name == 'push' && github.ref_name || github.event.workflow_run.head_branch }}
          release-type: node
          package-name: surfgrad
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Refactor","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"test","section":"Tests","hidden":true}
            ]

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: NPM Publish Dry Run
        run: npm publish --dry-run
        if: ${{ steps.release.outputs.release_created }}